// <auto-generated />
namespace LogginPage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PropertiesAdded9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropertiesAdded9));
        
        string IMigrationMetadata.Id
        {
            get { return "202202061323223_PropertiesAdded9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
